services:
  postgres:
    image: postgres
    container_name: partnerleads
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - adminjs-network

  adminjs:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: adminjs
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - COOKIE_SECRET=${COOKIE_SECRET}
    ports:
      - '3000:3000'
    networks:
      - adminjs-network
    volumes:
      - .:/src/app

networks:
  adminjs-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
